fastlane_version "1.36.4"

default_platform :ios

platform :ios do
  before_all do
  end

  lane :test_appium do
    
  end

  lane :test_calabash do
    
  end

  lane :test_ui_automation do
    
  end

  lane :test_xc_tests do
    
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end

