fastlane_version "1.36.4"

default_platform :ios

platform :ios do
  before_all do
  end

  lane :build do |params|
    xcodebuild(
      scheme: params[:scheme],
      build: true,
      sdk: "iphonesimulator",
      derivedDataPath: "build",
      xcargs: {
        ONLY_ACTIVE_ARCH: "NO"
      }
    )
  end

  lane :test_appium do
    build(
      scheme: "Contacts"
    )

    sh "cd ../appium && cucumber"
  end

  lane :test_calabash do
    build(
      scheme: "Contacts-cal"
    )
    
    sh "export APP_BUNDLE_PATH=\"../Build/Products/Debug-iphonesimulator/Contacts-cal.app\""
    sh "cd ../calabash && cucumber"
  end

  lane :test_ui_automation do
    
  end

  lane :test_xc_tests do
    scan(
      scheme: "Contacts"
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end