fastlane_version "1.36.4"

default_platform :ios

platform :ios do
  before_all do
  end

  lane :build do
    xcodebuild(
      scheme: "Contacts",
      build: true,
      sdk: "iphonesimulator",
      derivedDataPath: "build",
      xcargs: {
        ONLY_ACTIVE_ARCH: "NO"
      }
    )
  end

  lane :test_appium do
    build
    sh "cd ../appium && cucumber"
  end
  
  lane :test_calabash do
    
  end

  lane :test_ui_automation do
    
  end

  lane :test_xc_tests do
    
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end